apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java17
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "false"  # Disable online mode
            - name: "TYPE"
              value: "SPIGOT"
            - name: VERSION
              value: "1.19.4"
            - name: MEMORY
              value: "3G"
            - name: DIFFICULTY
              value: "normal"
          resources:
            requests:
              memory: "3Gi"
              cpu: "1500m"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
  selector:
    app: minecraft-server
